### ISSUE TITLE
colors.json missing in pypi

### ISSUE THREAD

**Issue by lmssdd** [tpvasconcelos/ridgeplot#1]
The file is not included and importing ridgeplot gives a FileNotFoundError

**Comment by tpvasconcelos** [comment]
@lmssdd thanks for pointing it out! 

This went unnoticed in the previous release. I just pushed a new release with the patch. If you update, everything should work now.
```shell
$ pip install -U ridgeplot
```

Double-check you got the right version
```shell
$ python -c "from ridgeplot import __version__; print(__version__)"
0.1.11
```

Let me know if this solved your problem 👍

**Comment by lmssdd** [comment]
Solved, thanks!
