### ISSUE TITLE
Add hover information

### ISSUE THREAD

**Issue by cpsievert** [tpvasconcelos/ridgeplot#152]
Nice package! It'd be great if hover information was included

**Comment by tpvasconcelos** [comment]
Hey @cpsievert thanks for opening this issue! I agree this is a good feature to add. It should even be the default behaviour. 

Is this something you're interested in taking a look at yourself and maybe contributing to the project?

**Comment by tpvasconcelos** [comment]
@cpsievert I'm implementing this in https://github.com/tpvasconcelos/ridgeplot/pull/174. What do you think of this as the default behaviour for the hover info displayed? I think it emulates Plotly's default behaviour close enough. Will merge and release this soon 👍 

<img width="904" alt="image" src="https://github.com/tpvasconcelos/ridgeplot/assets/17701527/3eff4d9a-7a63-4b2e-aa65-46df3c179682">

**Comment by tpvasconcelos** [comment]
@cpsievert see some interactive examples here (PR docs): https://ridgeplot--174.org.readthedocs.build/en/174/getting_started/getting_started.html

**Comment by tpvasconcelos** [comment]
@cpsievert just released this. If you upgrade (`pip install 'ridgeplot==0.1.24'`) you should be able to see the hover info by default. Feedback is welcome!
