### ISSUE TITLE
Different colors or colormaps for different data series

### ISSUE THREAD

**Issue by lorenzoamir** [tpvasconcelos/ridgeplot#215]
Hi, thank you for this package.
I was wandering if it was possible to have the colors (or colormaps) represent categorical data. For example, in the minimum and maximum temperature example in the documentation, have all data regarding minimum temperature in blue and data regarding maximum temperatures in red.
I made an example image of what I would like to achieve:
![image](https://github.com/user-attachments/assets/efaeb35f-dcc1-46c5-96cc-e6cac4218fe0)
Thank you

**Comment by tpvasconcelos** [comment]
Ciao @lorenzoamir! Thanks for submitting this feature request and providing a clear example plot right away! I love the idea and I've thought about implementing this in the past but never had the time. I'll try to have a look at it and make a quick assessment of the effort required. 

For these sort of changes, I always have to consider backwards compatibility, updates to the current documentation, user experience, how the API should look like and its impacts on the long-term maintainability of the project, etc...

If you already have a good idea of how you think the API could look like from the user's perspective let me know.

**Comment by tpvasconcelos** [comment]
From the top of my head, we could either somehow tap into the existing `colorscale` and `colormode` parameters to allow for this behaviour, or add an extra `colors` parameter that allows arbitrary colors to be passed for each individual trace. 

I think I prefer the first option as adding yet anther _"color"_ parameter would make things more confusing for end users, given that we already have `colorscale`, `colormode`, and `coloralpha`.

**Comment by lorenzoamir** [comment]
I agree. Maybe something like passing a list of colors to the `colorscale` parameter could work. Unfortunately I really don't have the time to work on it at the moment.

**Comment by tpvasconcelos** [comment]
I think that the change that requires the least amount of changes is to introduce a new colormode (e.g. trace-index-row-wise) that will take the index of each row's trace (0 and 1 in your example) and use that to grab colors form a colorscale.

In your example, the colorscale would have these two entries only:

```python
(
    (0.0, "red"),
    (1.0, "blue"),
)
```

I'll try to work on a draft pull request today.

**Comment by tpvasconcelos** [comment]
I got the example bellow with these two settings:

```python
fig = ridgeplot(
    # ...
    colorscale=(
        (0.0, "rgb(20, 20, 255)"),
        (1.0, "rgb(255, 20, 20)"),
    ),
    colormode="trace-index-row-wise",
    # ...
)
```

![image](https://github.com/user-attachments/assets/f8b9ba02-a4c4-48ba-86aa-76cb79e1a71d)

**Comment by tpvasconcelos** [comment]
@lorenzoamir what do you think of this interface for now?

**Comment by tpvasconcelos** [comment]
PR (WIP): #224 
New docs section (WIP): https://ridgeplot--224.org.readthedocs.build/en/224/getting_started/getting_started.html#coloring-options

**Comment by tpvasconcelos** [comment]
Ideally, ridgeplot should probably use the same conventions used by Plotly express for both continuous and discrete coloring options.

Here are the official references:
- https://plotly.com/python/colorscales/
- https://plotly.com/python/builtin-colorscales/
- https://plotly.com/python/discrete-color/

I'll create a new issue for this.

**Comment by tpvasconcelos** [comment]
FYI: In the latest version of ridgeplot you can use the following simplified notation:

```python
import numpy as np
from ridgeplot import ridgeplot

# Generate some sample data
my_samples = [
    [
        np.random.normal(n, size=600),
        np.random.normal((n + 1), size=600),
    ]
    for n in range(4, 0, -2)
]

# Create a ridgeplot and color the traces per row as red and blue
fig = ridgeplot(
    samples=my_samples,
    colorscale=["red", "blue"],
    colormode="trace-index-row-wise",
    coloralpha=0.9,
    linewidth=0,
)
fig.update_layout(height=450, width=800)
fig.show()
```

![image](https://github.com/user-attachments/assets/5f500c99-8e04-4e19-ac8b-f9785f9c896e)


Again, for the ones interested, the progress in adding more coloring modes can be found in #226
