### ISSUE TITLE
[BUG] Index-based colormodes raise `ZeroDivisionError` for single-trace plots

### ISSUE THREAD

**Issue by tpvasconcelos** [tpvasconcelos/ridgeplot#252]
All index-based colormodes raise a `ZeroDivisionError` when plotting a ridgeline plot with either a single trace or a single trace per row.

The index-based colormodes are:

```python
colormodes = [
    "row-index",
    "trace-index",
    "trace-index-row-wise",
]
```

MVE:

```pycon
>>> from ridgeplot import ridgeplot
>>> ridgeplot(samples=[[1, 2, 2, 3]], colormode=colormodes[0])
Traceback (most recent call last):
...
  File "[...]/ridgeplot/_color/interpolation.py", line 68, in _interpolate_row_index
    [((ctx.n_rows - 1) - ith_row) / (ctx.n_rows - 1)] * len(row)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

**Comment by sstephanyy** [comment]
@tpvasconcelos oops, I skipped the math classes 🥺 :rofl: . Please, give me some tips (without giving me the final answer) how could I debug to solve this bug.

**Comment by tpvasconcelos** [comment]
If you are interested in giving it at try, you could consider taking a look at [TDD](https://en.wikipedia.org/wiki/Test-driven_development) as a methodology to help arrive at the solution faster. i.e., 
1. Define some tests cases that should work. These will currently fail and raise the `ZeroDivisionError` exception
2. Debug the issue and make the necessary changes until all tests pass (including all existing tests)
3. Once all tests are green, refactor the code until you're happy with the final result (making sure that the tests never stop passing)
4. Done!

**Comment by sstephanyy** [comment]
> If you are interested in giving it at try, you could consider taking a look at [TDD](https://en.wikipedia.org/wiki/Test-driven_development) as a methodology to help arrive at the solution faster. i.e.,
> 
>     1. Define some tests cases that should work. These will currently fail and raise the `ZeroDivisionError` exception
> 
>     2. Debug the issue and make the necessary changes until all tests pass (including all existing tests)
> 
>     3. Once all tests are green, refactor the code until you're happy with the final result (making sure that the tests never stop passing)
> 
>     4. Done!

Thanks so much @tpvasconcelos . I'll give it a try :smiley:

**Comment by tpvasconcelos** [comment]
Thanks @sstephanyy ! 🚀
