### ISSUE TITLE
Automatically generate the `docs/api/internal/*.rst` files

### ISSUE THREAD

**Issue by tpvasconcelos** [tpvasconcelos/ridgeplot#290]
These files need to be manually kept in sync which is a lot of work and error-prone. Would be better to maintain the project's entire API docs in a more automated way

---

The ridgeplot [API docs](https://ridgeplot.readthedocs.io/en/latest/api/) include a `Internals` section that should include the entire project's documentation

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/0ec5c984-acbf-4cc8-8777-d2eafd52c25e">

Currently, each sub-package (e.g. `ridgeplot._color`) is documented in a separate page.

<img width="1477" alt="image" src="https://github.com/user-attachments/assets/a52ba2f6-745b-4c4d-8944-bd311dca5147">

However, this does not need to be the case. I am okay (and maybe even prefer) if we list all modules in the main API doc page and then a single doc page per module. i.e.,

- [ridgeplot._color](https://ridgeplot.readthedocs.io/en/latest/api/internal/color.html)
  - [ridgeplot._color.colorscale](https://ridgeplot.readthedocs.io/en/latest/api/internal/_color/colorscale.html)
  - [ridgeplot._color.css_colors](https://ridgeplot.readthedocs.io/en/latest/api/internal/_color/css_colors.html)
  - [ridgeplot._color.interpolation](https://ridgeplot.readthedocs.io/en/latest/api/internal/_color/interpolation.html)
  - [ridgeplot._color.utils](https://ridgeplot.readthedocs.io/en/latest/api/internal/_color/utils.html)
- [ridgeplot._figure_factory](https://ridgeplot.readthedocs.io/en/latest/api/internal/figure_factory.html)
- [ridgeplot._hist](https://ridgeplot.readthedocs.io/en/latest/api/internal/hist.html)
- [ridgeplot._kde](https://ridgeplot.readthedocs.io/en/latest/api/internal/kde.html)
- [ridgeplot._missing](https://ridgeplot.readthedocs.io/en/latest/api/internal/missing.html)
- [ridgeplot._obj](https://ridgeplot.readthedocs.io/en/latest/api/internal/obj.html)
  - [ridgeplot._obj.traces](https://ridgeplot.readthedocs.io/en/latest/api/internal/_obj/traces.html)
- [ridgeplot._types](https://ridgeplot.readthedocs.io/en/latest/api/internal/types.html)
- [ridgeplot._utils](https://ridgeplot.readthedocs.io/en/latest/api/internal/utils.html)

--- 

The way that we currently implement and maintain the current solution is to represent the package structure and modules in RST files, with each RST file containing a `.. automodule:: ridgeplot._color.css_colors` directive.

<img width="279" alt="image" src="https://github.com/user-attachments/assets/45c31693-4340-4577-a367-832b627007f3">

Note that currently each module contains a short description inside each RST file (e.g., _"Continuous colorscale utilities."_ for `ridgeplot._color.colorscale`). This could probably be represented as a module docstring when considering a more automated approach.

--

The solution to this problem is not clear to me. Maybe there are already tools out there that solve this nicely (e.g. `sphinx.ext.autodoc`, `sphinx.ext.autosummary`, `sphinx_toolbox.more_autodoc`, etc...). We could take a look at other prominent projects in the Python open-source space that currently use Sphinx and autodoc for API documentation.

**Comment by imprvhub** [comment]
hi @tpvasconcelos can i contribute to this issue? maybe you can assign me? thanks!

**Comment by tpvasconcelos** [comment]
Hi @imprvhub, thanks for the interest! I'll update the issue description now with some more context. Let me know if you need me to specify anything else.

**Comment by tpvasconcelos** [comment]
@imprvhub Ideally this would be integrated in the CI pipeline such that, when a new module is added, the new code won't be merged until this is reflected in the API docs. Maybe this won't be an issue if the automated solution will generate the package tree and module docs on the fly during the documentation build step

**Comment by imprvhub** [comment]
Hi @tpvasconcelos,

Apologies for the delay—it's been a hectic start to the week!

I’m actively working on the solution. The script I’ve created so far generates the .rst files with everything required. However, I’ve run into an issue with modules that have lengthy descriptions, like src/ridgeplot/_ridgeplot.py.

I’m currently looking into the best way to address this and aim to have it resolved by tomorrow at the latest.

Thanks for your patience, and I’ll keep you updated! 😊

**Comment by imprvhub** [comment]
Hi @tpvasconcelos,

I’ve just pushed the PR to automate the generation of the .rst files. I think it’s all working correctly, but if you could give it a try and let me know your thoughts, that’d be great. If there’s anything that can be improved, I’m definitely open to suggestions.

Thanks for the chance to contribute to the project!
