### ISSUE TITLE
Add normalisation options

### ISSUE THREAD

**Issue by marclelamy** [tpvasconcelos/ridgeplot#3]
Hi! 

First, thanks for this library which is really awesome! 

I have this dataset where I'm analyzing Premie league football since 1992. I want to plot a Ridge plot with each subplot being Yellow_card, red_card, goal, penalty, etc, and see the distribution over a 90mn period to see when these actions happen the most. Of course, there is way more yellow cards than goals and way more goals that red card which results in a plot like this:

<img src="https://i.ibb.co/SVCwQrG/Screenshot-2021-07-13-at-01-29-37.png" alt="Screenshot-2021-07-13-at-01-29-37" border="0">

Is there a way to see everything, I check the parameters and the code but I'm not that good in python to understand everything yet...

Any help?

**Comment by tpvasconcelos** [comment]
@marclelamy thank you for the kind words!

This looks like a nice feature to implement. I will have a look at this in the coming days. In the meantime, you could achieve this by normalising each trace yourself. Let me get back to you on this 🚀

**Comment by tpvasconcelos** [comment]
@marclelamy any success? Let me know if you would like some help in the meantime :)

**Comment by marclelamy** [comment]
Hey! I just logged back on Github but went with the Plotly solution as I found it works pretty well. But yeah, now that you talk about normalization, it totally makes sense and I'm sure it would work!

**Comment by tpvasconcelos** [comment]
Thanks for getting back to me @marclelamy!  I have added an [**enhancement**](https://github.com/tpvasconcelos/ridgeplot/labels/enhancement) label to this as I still believe it is a nice feature to add 🚀
