### ISSUE TITLE
No ability to plot different densities on the same ridgeplot 

### ISSUE THREAD

**Issue by dariakhaetskaya** [tpvasconcelos/ridgeplot#77]
Great work, thanks a lot! I'm looking for a way to plot different approximations on the same ridgeplot. I need to compare KDE and my custom density approximation. Adding traces is currently impossible cause method returns figure and there's no way to add traces to every single density subplot.

If you know a way to do that, please let me know! Thanks in advance

**Comment by dariakhaetskaya** [comment]
Here's an example of a plot that I need 
![image](https://user-images.githubusercontent.com/68292792/211271554-0a532d4d-e865-4cab-8c5c-efdc55fb11d9.png)

**Comment by tpvasconcelos** [comment]
I think this is a great idea. Let me know if you'd like to contribute to this feature. Otherwise, I'll take a look 👍

**Comment by dariakhaetskaya** [comment]
I did some hacks locally for getting what I want but I think we need to think it over and decide what the interface for this option should be (for example builder may have method that adds density to ridgeplot?). I know that in R language you can add as many densities as you want, maybe it'll be helpful to take a closer look. I'm currently busy preparing for exams but I can work on this feature after Jan 17th.

**Comment by dariakhaetskaya** [comment]
Hey! I have troubles recalculating min and max for multiple densities. It should be just `get_xy_extrema(density1 + density2)` but when plotted it looks like it has been cut in half. Also, I sometimes get an exception:
`RuntimeError: Selected KDE bandwidth is 0. Cannot estimate density. Either provide the bandwidth during initialization or use an alternative method.`
When I call `get_densities` function. Silverman and Scott rules are great for normal distributions, but I work with multimodal data and these rules just fail to select bandwidth. I recommend using Sheather and Jones method [https://www.jstor.org/stable/2345597]. There's a great comparison here https://aakinshin.net/posts/kde-bw/

**Comment by tpvasconcelos** [comment]
> I did some hacks locally for getting what I want but I think we need to think it over and decide what the interface for this option should be (for example builder may have method that adds density to ridgeplot?). I know that in R language you can add as many densities as you want, maybe it'll be helpful to take a closer look. I'm currently busy preparing for exams but I can work on this feature after Jan 17th.

I will try to take a look at this in the coming days. Currently busy with other projects. Currently, the `densities` argument expects an iterable of 2D array-like objects. For example: `[[1, 2, 3, 4], [5, 6, 7, 8]]`. We could change this to also accept 3D arrays like `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]`. This allows the user to pass multiple density traces per line/group. Sounds like a simple change as well :)

**Comment by tpvasconcelos** [comment]
> I have troubles recalculating min and max for multiple densities. It should be just get_xy_extrema(density1 + density2) but when plotted it looks like it is cut in half.

Sounds like your `density1` and `density2` are numpy arrays? If you add them together with the `+` operator, it makes sense that you'll get unexpected results out of `get_xy_extrema()`. Does this make sense?

**Comment by tpvasconcelos** [comment]
Hey @dariakhaetskaya! Thanks again for showing interest in the project and contributing to this feature!! 🚀🚀

> I did some hacks locally for getting what I want but I think we need to think it over and decide what the interface for this option should be (for example builder may have method that adds density to ridgeplot?). I know that in R language you can add as many densities as you want, maybe it'll be helpful to take a closer look. I'm currently busy preparing for exams but I can work on this feature after Jan 17th.

Currently, the `densities` argument expects an iterable of 2D array-like objects. For example: `[[1, 2, 3, 4], [5, 6, 7, 8]]`. We could change this to also accept 3D arrays like `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]`. This allows the user to pass multiple density traces per line/group. Sounds like a simple change as well :) 

> I have troubles recalculating min and max for multiple densities. It should be just `get_xy_extrema(density1 + density2)` but when plotted it looks like it is cut in half.

Sounds like your `density1` and `density2` are numpy arrays? If you add them together with the `+` operator, it makes sense that you'll get unexpected results out of `get_xy_extrema()`. Does this make sense?

> Also, I sometimes get an exception:
> `RuntimeError: Selected KDE bandwidth is 0. Cannot estimate density. Either provide the bandwidth during initialization or use an alternative method.`
> When I call `get_densities` function. 

I've experienced `statsmodels` to be a bit flaky here too.... :/ Do you have some concrete examples?

> Silverman and Scott rules are great for normal distributions, but I work with multimodal data and these rules just fail to select bandwidth. I recommend using Sheather and Jones method [https://www.jstor.org/stable/2345597]. There's a great comparison here https://aakinshin.net/posts/kde-bw/

Can you elaborate on what you mean here?

**Comment by tpvasconcelos** [comment]
I will try to take a look at this with better eyes in the coming days :)

**Comment by tpvasconcelos** [comment]
Hey @dariakhaetskaya! I am about to release some changes that make it possible to draw multiple lines per row.

Here is an example:

```python
import pandas as pd
import numpy as np
from ridgeplot import ridgeplot
# from ridgeplot.datasets import load_lincoln_weather

# Load test data
# df = load_lincoln_weather()
df = pd.read_csv(
    "https://raw.githubusercontent.com/wilkelab/ggridges/master/data-raw/lincoln-weather.csv",
    index_col="CST",
    parse_dates=True,
)

# Transform the data into a 3D (ragged) array format of
# daily min and max temperature samples per month
months = df.index.month_name().unique()
samples = [
    [
        df[df.index.month_name() == month]["Min Temperature [F]"],
        df[df.index.month_name() == month]["Max Temperature [F]"],
    ]
    for month in months
]

# And finish by styling it up to your liking!
fig = ridgeplot(
    samples=samples,
    labels=months,
    coloralpha=0.98,
    bandwidth=4,
    kde_points=np.linspace(-25, 110, 400),
    spacing=0.33,
    linewidth=2,
)
fig.update_layout(
    title="Minimum and maximum daily temperatures in Lincoln, NE (2016)",
    height=650,
    width=950,
    font_size=14,
    plot_bgcolor="rgb(245, 245, 245)",
    xaxis_gridcolor="white",
    yaxis_gridcolor="white",
    xaxis_gridwidth=2,
    yaxis_title="Month",
    xaxis_title="Temperature [F]",
    showlegend=False,
)
fig.show()
```

![](https://user-images.githubusercontent.com/17701527/260071282-84db6057-83f1-461e-9a8c-6e08b911c3e8.png)
